name: "Build Test - Windows on ARM Meson Clang"

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-11-arm ]

    name: Windows Meson build & test 
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ github.event.pull_request.commits }}
      - name: Install submodules
        run: git submodule sync && git submodule update --init --recursive
      - name: Install Python Dependencies
        run: pip install meson==1.7.2 ninja
      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: arm64
      - name: Prepare Build
        run: meson setup --native-file windows-native-clang.ini builddir
      - name: Run Build
        run: meson compile -C builddir
      - name: Run Test Suite
        run: meson test -C builddir
